### ISSUE TITLE
Implement language buttons as in design 

### ISSUE THREAD

**Issue by cyclomaticcomplexity1981** [plante-app-team/plante-website#3]
**Description**
Design the language buttons as in the design by UX.

**Framer**
https://framer.com/share/y4CDw4vCAFJnRBx1g9w5/nTZkx3tmb

**jira**
https://plante.atlassian.net/browse/PW-6

**Comment by nguyendang127** [comment]
can I resolve this issue !!!

**Comment by cyclomaticcomplexity1981** [comment]
Sure! Have fun with it. Can you see the ux design? Else i'll get you some screenshots and video.

**Comment by nguyendang127** [comment]
Yes, I saw the UX but if you don't mind send me some sreenshots and video. Thank you so much

**Comment by blazern** [comment]
> Yes, I saw the UX but if you don't mind send me some sreenshots and video. Thank you so much

Hello @nguyendang127!
Here's a video: https://youtu.be/zclMr_K23rQ
Here's a screenshot: 
![image](https://user-images.githubusercontent.com/3338378/141077064-9c89162d-8559-4e11-963e-392dc769df32.png)

**Comment by cyclomaticcomplexity1981** [comment]
Currently we have implemented a lot more languages, waiting for design to shift to a dropdown or other solution
